# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170804_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='author',
            field=models.CharField(default='남택호', max_length=10),
        ),
        migrations.AlterField(
            model_name='api',
            name='desc',
            field=models.CharField(max_length=30, verbose_name='API 요약'),
        ),
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(max_length=20, verbose_name='API 명'),
        ),
    ]
