# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170804_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='author',
            field=models.CharField(default='남택호', max_length=100),
        ),
    ]
