# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-15 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170804_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='desc',
            field=models.CharField(max_length=100, verbose_name='API 요약'),
        ),
    ]
